### ISSUE TITLE
Callback should accept a string

### ISSUE THREAD

**Issue by jeznag** [darbio/aws-lambda-typescript#2]
https://docs.aws.amazon.com/apigateway/latest/developerguide/handle-errors-in-lambda-integration.html

Lambda proxy integration requires errors to be passed as a stringified JSON object.

**Comment by darbio** [comment]
Hi @jeznag - thanks for the issue. This repo was merged into definitely typed a while back and has had a number of changes made to it to bring it up to speed since then. Can you check over there to see if this has already been fixed?

**Comment by jeznag** [comment]
I couldn't see a fix so created a PR: https://github.com/DefinitelyTyped/DefinitelyTyped/pull/26096
